### PR TITLE
Move to the APi from sbidin/sdl2-ttf

### PR DESCRIPTION
**Pull request by Mikolaj**
See #2.

My only serious worry with the API change is that some people may be using Strings, not Texts. In that case, wrapping the string in `Text.pack` will probably still result in much faster calls than with the original API, but should we explicitly provide String versions of the functions? If so, can we make them faster than via `Text.pack`?

### CODE REVIEW

**Comment by rongcuid** [comment]
Wow, that is a lot of commits. Which one are you pointing to? Is it possible to clean up the commit logs (maybe cherrypick or rebase, I don't remember exactly).

**Comment by Mikolaj** [comment]
Hi @rongcuid! This PR is actually a very brave proposal to, basically, merge the two sdl-ttf repos, apply some fixes from your repo to sbidin's (most of my commits above basically do that) and then completely replace your old API with sbidin's, because it's more in sync with the core SDL2 bindings wrt naming, conventions, TH tooling, etc. and also a bit more complete. I guess it was just done more recently and was using the accumulated knowledge base and tooling of the SDL2 contributors.

I've checked, more or less, that both code-bases bind the foreign exports in the same way (except for the "unsafe" bit, see #2) and only differ in the high level bindings, but also only in a few (in particular in the ones that covert  `Text` to `CString` in a very efficient and evidently correct way). Please correct me, if I missed anything.

So, most of the commits are just the complete history of sbidin's repo and only my commits perform the actual merge of features, both ways. I'm fully aware that what I propose is very brutal, but I'm willing to help users adapt to the new API (in their code or adding some backward compatibility layer, if needed). :)

**Comment by rongcuid** [comment]
Well I am not talking about how radical the changes are (because I know my repo was far far behind because I was not doing any game experiments for a long time). I am saying could you make the pull request a bit more readable, like making another branch with a single commit? I (or other maintainers) will need to see what the pull request changes.

I might actually not be the one who merge it, though, since I will need to set up the dev environment again... Anyways, I will try to understand the code

**Comment by Mikolaj** [comment]
Is this branch more readable: https://github.com/Mikolaj/sdl2-ttf/tree/API-change  ? I've squashed all the history from sbidin's repo.

BTW, technically, I could merge the PR or perhaps some kind folk from @haskell-game would.

**Comment by Mikolaj** [comment]
@rongcuid: ^^^

Can I help you in the review in any way? In my case, I've found it helpful to locally generate haddocks for both repos and compare them visually side by side --- that's how I know the raw bindings are very close, even wrt naming.

**Comment by rongcuid** [comment]
If you find it appropriate, I think it is OK. As I said, I would not be developing games in recent times. However, I don't own the sdl2-ttf package on Hackage, would that matter?

**Comment by Mikolaj** [comment]
Oh, great, thank you, let's do this, then. I'm merging now and I will assist in handling any fallout from this merge. Let me also ask guys about Hackage, but on another thread.

**Pull request merged**
